spring.datasource.url=jdbc:mysql://localhost:3306/mercasuper
spring.datasource.username=root
spring.datasource.password=
# Cambia 'none' por 'update' para que Spring cree las tablas si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Deja que Spring elija el dialecto autom\u00e1ticamente
server.port=8080