spring.datasource.url=jdbc:mysql://localhost:3306/mercasuper
spring.datasource.username=root
spring.datasource.password=
# 'update' sincroniza tu clase Java con la tabla de MySQL autom\u00e1ticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Cambiamos el puerto al 8085 para evitar conflictos en NetBeans
server.port=8085